name: Postman API Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        
    - name: Run Postman Collection
      run: |
        newman run collections/qa.postman_collection.json \
        --reporters cli,htmlextra \
        --reporter-htmlextra-export newman-report.html
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: newman-report
        path: newman-report.html